In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn.objects as so
import warnings
warnings.filterwarnings('ignore')

# 데이터 불러오기
merged = pd.read_csv('final_data.csv', index_col=0)
merged

,index,district_1,district_2,stn,ta_max,ta_min,ta_max_min,rn_day,ws_max,ws_ins_max,...,dead,injury,property_damage,location_category_1,location_category_2,location_category_3,month_y,ym,hour,season
0,0,서울특별시,종로구,108,3.8,-5.1,8.9,0.0,3.8,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,서울특별시,종로구,108,1.8,-4.3,6.1,0.0,4.9,8.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,서울특별시,종로구,108,-0.4,-7.1,6.7,0.0,3.5,6.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,서울특별시,종로구,108,-0.7,-8.7,8.0,0.0,3.5,5.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,서울특별시,종로구,108,1.6,-5.6,7.2,0.0,3.6,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554293,558231,강원특별자치도,양양군,670,6.6,-3.0,9.6,0.0,4.1,5.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554294,558232,강원특별자치도,양양군,670,7.4,-3.8,11.2,0.0,6.5,10.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554295,558233,강원특별자치도,양양군,670,9.3,1.6,7.7,0.0,7.2,10.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554296,558234,강원특별자치도,양양군,670,6.0,1.4,4.6,0.5,5.8,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554297,558235,강원특별자치도,양양군,670,3.0,0.6,2.4,11.0,5.2,7.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# 태백산맥 일대의 데이터만 정리
gangwon = merged.query('district_1=="강원특별자치도" and district_2 in ["정선군", "평창군", "태백시", "인제군", "양구군", "삼척시", "강릉시"]')
gangwon.to_csv('gangwon.csv')

gyeongbuk = merged.query('district_1=="경상북도" and district_2 in ["울진군", "영덕군", "영양군"]')
gyeongbuk.to_csv('gyeongbuk.csv')

taebaek_mountain = pd.concat([gangwon, gyeongbuk])
taebaek_mountain.to_csv('taebaek_mountain.csv')